<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'FratellanzaMilitare\\Queue\\QueueInterface' => 'get1',
  'FratellanzaMilitare\\Controller\\SettingsController' => 'get2',
  'FratellanzaMilitare\\Controller\\HomeController' => 'get3',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsSystemController' => 'get4',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsAuditController' => 'get5',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsDashboardController' => 'get6',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsFileSystemController' => 'get7',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsDatabaseController' => 'get8',
  'FratellanzaMilitare\\Controller\\DevTools\\DevToolsSecurityController' => 'get9',
  'FratellanzaMilitare\\Controller\\Intelligence\\StatsDashboardController' => 'get10',
  'FratellanzaMilitare\\Controller\\Intelligence\\ReportExportController' => 'get11',
  'FratellanzaMilitare\\AI\\Providers\\OllamaProvider' => 'get12',
  'FratellanzaMilitare\\AI\\RAG\\SimpleVectorStore' => 'get13',
  'FratellanzaMilitare\\Service\\DocumentParser\\PdfParserService' => 'get14',
  'FratellanzaMilitare\\Service\\DocumentParser\\WordParserService' => 'get15',
  'FratellanzaMilitare\\Service\\DocumentParser\\ExcelParserService' => 'get16',
  'FratellanzaMilitare\\Service\\DocumentParser\\CodeParserService' => 'get17',
  'FratellanzaMilitare\\Service\\DocumentParser\\DocumentParserFactory' => 'get18',
  'FratellanzaMilitare\\AI\\RAG\\DocumentChunkerService' => 'get19',
  'FratellanzaMilitare\\Service\\AI\\DocumentIngestionService' => 'get20',
  'FratellanzaMilitare\\Controller\\AI\\AssistantController' => 'get21',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\ListController' => 'get22',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\DetailController' => 'get23',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\PersistenceController' => 'get24',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\ActionController' => 'get25',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Documenti\\StorageController' => 'get26',
  'FratellanzaMilitare\\Controller\\Anagrafica\\Servizi\\SocioExportController' => 'get27',
  'FratellanzaMilitare\\Controller\\Auth\\LoginFlowController' => 'get28',
  'FratellanzaMilitare\\Controller\\Auth\\TwoFactorController' => 'get29',
  'FratellanzaMilitare\\Controller\\Auth\\LogoutController' => 'get30',
  'FratellanzaMilitare\\Service\\RedisService' => 'get31',
  'FratellanzaMilitare\\Service\\CacheService' => 'get32',
  'FratellanzaMilitare\\Service\\QueueService' => 'get33',
  'FratellanzaMilitare\\Service\\BackupVerificationService' => 'get34',
  'FratellanzaMilitare\\Service\\HealthCheckService' => 'get35',
  'FratellanzaMilitare\\Service\\JsonLogFormatter' => 'get36',
  'FratellanzaMilitare\\Service\\ValidationService' => 'get37',
  'FratellanzaMilitare\\Service\\BackupService' => 'get38',
  'FratellanzaMilitare\\Debug\\ResilienceMonitor' => 'get39',
  'FratellanzaMilitare\\Service\\EmailServiceInterface' => 'get40',
  'FratellanzaMilitare\\Service\\PdfGenerationService' => 'get41',
  'FratellanzaMilitare\\Service\\RegistrationService' => 'get42',
  'FratellanzaMilitare\\Service\\Demo\\DemoInvitationService' => 'get43',
  'FratellanzaMilitare\\Event\\EventBusInterface' => 'get44',
  'FratellanzaMilitare\\Event\\Listeners\\IndexSocioListener' => 'get45',
  'Psr\\Log\\LoggerInterface' => 'get46',
  'audit_logger' => 'get47',
  'Predis\\Client' => 'get48',
  'PDO' => 'get49',
  'FratellanzaMilitare\\InfrastrutturaIT\\Persistence\\PDOSocioRepository' => 'get50',
  'FratellanzaMilitare\\GestioneSoci\\SocioRepository' => 'get51',
  'Mustache_Engine' => 'get52',
  'FratellanzaMilitare\\SecurityLayer\\AuditTrail' => 'get53',
  'HTMLPurifier' => 'get54',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $pdo = $c->get(\PDO::class);
        return new \FratellanzaMilitare\Queue\DatabaseQueue($pdo);
    }, 'FratellanzaMilitare\\Queue\\QueueInterface');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\SettingsController($c->get(\Mustache_Engine::class));
    }, 'FratellanzaMilitare\\Controller\\SettingsController');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\HomeController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\GestioneSoci\SocioRepository::class)
        );
    }, 'FratellanzaMilitare\\Controller\\HomeController');
    }

    protected function get4()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsSystemController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\Debug\ResilienceMonitor::class),
            $c->get(\PDO::class)
        );
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsSystemController');
    }

    protected function get5()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsAuditController(
            $c->get(\Mustache_Engine::class),
            $c->get(\PDO::class)
        );
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsAuditController');
    }

    protected function get6()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsDashboardController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\Controller\DevTools\DevToolsSystemController::class),
            $c->get(\FratellanzaMilitare\Controller\DevTools\DevToolsAuditController::class),
            $c->get(\FratellanzaMilitare\Service\Demo\DemoInvitationService::class)
        );
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsDashboardController');
    }

    protected function get7()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsFileSystemController();
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsFileSystemController');
    }

    protected function get8()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsDatabaseController(
            $c->get(\Mustache_Engine::class)
        );
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsDatabaseController');
    }

    protected function get9()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Controller\DevTools\DevToolsSecurityController();
    }, 'FratellanzaMilitare\\Controller\\DevTools\\DevToolsSecurityController');
    }

    protected function get10()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Intelligence\StatsDashboardController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\GestioneSoci\SocioRepository::class),
            $c->get(\FratellanzaMilitare\Debug\ResilienceMonitor::class),
            $c->get(\FratellanzaMilitare\Service\HealthCheckService::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Intelligence\\StatsDashboardController');
    }

    protected function get11()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Intelligence\ReportExportController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\GestioneSoci\SocioRepository::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Intelligence\\ReportExportController');
    }

    protected function get12()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        // Base URL da .env o default localhost
        $host = $_ENV['OLLAMA_HOST'] ?? 'http://127.0.0.1:11434';
        return new \FratellanzaMilitare\AI\Providers\OllamaProvider(
            $c->get(\Psr\Log\LoggerInterface::class),
            $host
        );
    }, 'FratellanzaMilitare\\AI\\Providers\\OllamaProvider');
    }

    protected function get13()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $storagePath = 'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../storage/ai/vector_store.json';
        return new \FratellanzaMilitare\AI\RAG\SimpleVectorStore(
            $c->get(\Psr\Log\LoggerInterface::class),
            $storagePath
        );
    }, 'FratellanzaMilitare\\AI\\RAG\\SimpleVectorStore');
    }

    protected function get14()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\DocumentParser\PdfParserService();
    }, 'FratellanzaMilitare\\Service\\DocumentParser\\PdfParserService');
    }

    protected function get15()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\DocumentParser\WordParserService();
    }, 'FratellanzaMilitare\\Service\\DocumentParser\\WordParserService');
    }

    protected function get16()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\DocumentParser\ExcelParserService();
    }, 'FratellanzaMilitare\\Service\\DocumentParser\\ExcelParserService');
    }

    protected function get17()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\DocumentParser\CodeParserService();
    }, 'FratellanzaMilitare\\Service\\DocumentParser\\CodeParserService');
    }

    protected function get18()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\DocumentParser\DocumentParserFactory($c);
    }, 'FratellanzaMilitare\\Service\\DocumentParser\\DocumentParserFactory');
    }

    protected function get19()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\AI\RAG\DocumentChunkerService();
    }, 'FratellanzaMilitare\\AI\\RAG\\DocumentChunkerService');
    }

    protected function get20()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\AI\DocumentIngestionService(
            $c->get(\FratellanzaMilitare\Service\DocumentParser\DocumentParserFactory::class),
            $c->get(\FratellanzaMilitare\AI\RAG\DocumentChunkerService::class),
            $c->get(\FratellanzaMilitare\AI\RAG\SimpleVectorStore::class),
            $c->get(\FratellanzaMilitare\AI\Providers\OllamaProvider::class)
        );
    }, 'FratellanzaMilitare\\Service\\AI\\DocumentIngestionService');
    }

    protected function get21()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\AI\AssistantController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\AI\Providers\OllamaProvider::class),
            $c->get(\FratellanzaMilitare\AI\RAG\SimpleVectorStore::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\FratellanzaMilitare\Queue\QueueInterface::class),
            $c->get(\FratellanzaMilitare\GestioneSoci\SocioRepository::class)
        );
    }, 'FratellanzaMilitare\\Controller\\AI\\AssistantController');
    }

    protected function get22()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Soci\ListController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\ListController');
    }

    protected function get23()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Soci\DetailController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository::class),
            $c->get('audit_logger')
        );
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\DetailController');
    }

    protected function get24()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Soci\PersistenceController(
            $c->get(\Mustache_Engine::class),
            $c->get(\FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository::class),
            $c->get('audit_logger'),
            $c->get(\FratellanzaMilitare\Service\ValidationService::class),
            $c->get(\FratellanzaMilitare\Service\RegistrationService::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\PersistenceController');
    }

    protected function get25()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Soci\ActionController($c->get('audit_logger'));
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Soci\\ActionController');
    }

    protected function get26()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Documenti\StorageController(
            $c->get(\FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository::class),
            $c->get('audit_logger'),
            $c->get(\FratellanzaMilitare\Service\ValidationService::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Documenti\\StorageController');
    }

    protected function get27()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Anagrafica\Servizi\SocioExportController(
            $c->get(\FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository::class),
            $c->get(\Mustache_Engine::class)
        );
    }, 'FratellanzaMilitare\\Controller\\Anagrafica\\Servizi\\SocioExportController');
    }

    protected function get28()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Auth\LoginFlowController(
            $c->get(\Mustache_Engine::class),
            new \FratellanzaMilitare\Service\InputValidator()
        );
    }, 'FratellanzaMilitare\\Controller\\Auth\\LoginFlowController');
    }

    protected function get29()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Controller\Auth\TwoFactorController($c->get(\Mustache_Engine::class));
    }, 'FratellanzaMilitare\\Controller\\Auth\\TwoFactorController');
    }

    protected function get30()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Controller\Auth\LogoutController();
    }, 'FratellanzaMilitare\\Controller\\Auth\\LogoutController');
    }

    protected function get31()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Service\RedisService();
    }, 'FratellanzaMilitare\\Service\\RedisService');
    }

    protected function get32()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\CacheService(
            $c->get(\FratellanzaMilitare\Service\RedisService::class)
        );
    }, 'FratellanzaMilitare\\Service\\CacheService');
    }

    protected function get33()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\QueueService(
            $c->get(\PDO::class)
        );
    }, 'FratellanzaMilitare\\Service\\QueueService');
    }

    protected function get34()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\BackupVerificationService(
            $c->get(\PDO::class),
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../storage/backups'
        );
    }, 'FratellanzaMilitare\\Service\\BackupVerificationService');
    }

    protected function get35()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\HealthCheckService(
            $c->get(\PDO::class),
            $c->get(\FratellanzaMilitare\Service\RedisService::class),
            $c->get(\FratellanzaMilitare\Service\QueueService::class),
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../storage'
        );
    }, 'FratellanzaMilitare\\Service\\HealthCheckService');
    }

    protected function get36()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Service\JsonLogFormatter('FratellanzaMilitare');
    }, 'FratellanzaMilitare\\Service\\JsonLogFormatter');
    }

    protected function get37()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Service\ValidationService();
    }, 'FratellanzaMilitare\\Service\\ValidationService');
    }

    protected function get38()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\BackupService(
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../database.sqlite',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../storage/backups',
            $c->get(\Psr\Log\LoggerInterface::class),
            14
        );
    }, 'FratellanzaMilitare\\Service\\BackupService');
    }

    protected function get39()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Debug\ResilienceMonitor(
            $c->get(\PDO::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../storage'
        );
    }, 'FratellanzaMilitare\\Debug\\ResilienceMonitor');
    }

    protected function get40()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $config = [
            'host' => $_ENV['SMTP_HOST'] ?? 'smtp.example.com',
            'username' => $_ENV['SMTP_USER'] ?? 'user@example.com',
            'password' => $_ENV['SMTP_PASS'] ?? 'secret',
            'port' => $_ENV['SMTP_PORT'] ?? 587
        ];
        return new \FratellanzaMilitare\Service\SmtpEmailService($c->get(\Psr\Log\LoggerInterface::class), $config);
    }, 'FratellanzaMilitare\\Service\\EmailServiceInterface');
    }

    protected function get41()
    {
        return $this->resolveFactory(static function () {
        return new \FratellanzaMilitare\Service\PdfGenerationService();
    }, 'FratellanzaMilitare\\Service\\PdfGenerationService');
    }

    protected function get42()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\RegistrationService(
            $c->get(\FratellanzaMilitare\GestioneSoci\SocioRepository::class),
            $c->get(\FratellanzaMilitare\Service\ValidationService::class),
            $c->get(\FratellanzaMilitare\Service\PdfGenerationService::class),
            $c->get(\FratellanzaMilitare\Service\EmailServiceInterface::class),
            $c->get(\Psr\Log\LoggerInterface::class)
        );
    }, 'FratellanzaMilitare\\Service\\RegistrationService');
    }

    protected function get43()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Service\Demo\DemoInvitationService(
            $c->get(\FratellanzaMilitare\Service\EmailServiceInterface::class),
            $c->get(\Psr\Log\LoggerInterface::class),
            $_ENV['APP_URL'] ?? 'http://localhost/fratellanza-militare-archivio/public',
            $c->get(\PDO::class)
        );
    }, 'FratellanzaMilitare\\Service\\Demo\\DemoInvitationService');
    }

    protected function get44()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $bus = new \FratellanzaMilitare\Event\EventBus($c->get(\Psr\Log\LoggerInterface::class));

        // Register Listeners
        // 1. Log Socio Creation
        $bus->subscribe(
            \FratellanzaMilitare\Event\Events\SocioCreatedEvent::class,
            new \FratellanzaMilitare\Event\Listeners\LogSocioCreationListener($c->get(\Psr\Log\LoggerInterface::class))
        );

        // 2. AI Indexing (RAG)
        $bus->subscribe(
            \FratellanzaMilitare\Event\Events\SocioCreatedEvent::class,
            $c->get(\FratellanzaMilitare\Event\Listeners\IndexSocioListener::class)
        );

        return $bus;
    }, 'FratellanzaMilitare\\Event\\EventBusInterface');
    }

    protected function get45()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        return new \FratellanzaMilitare\Event\Listeners\IndexSocioListener(
            $c->get(\Psr\Log\LoggerInterface::class),
            $c->get(\FratellanzaMilitare\AI\Providers\OllamaProvider::class),
            $c->get(\FratellanzaMilitare\AI\RAG\SimpleVectorStore::class)
        );
    }, 'FratellanzaMilitare\\Event\\Listeners\\IndexSocioListener');
    }

    protected function get46()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $logger = new \Monolog\Logger('system');
        $handler = new \Monolog\Handler\StreamHandler('C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../logs/app.log', \Monolog\Logger::DEBUG);
        $handler->setFormatter(new \Monolog\Formatter\JsonFormatter());
        $logger->pushHandler($handler);

        $processor = function ($record) {
            if (isset($_SERVER['HTTP_X_REQUEST_ID'])) {
                $record['extra']['request_id'] = $_SERVER['HTTP_X_REQUEST_ID'];
            }
            return $record;
        };
        $logger->pushProcessor($processor);
        return $logger;
    }, 'Psr\\Log\\LoggerInterface');
    }

    protected function get47()
    {
        return $this->resolveFactory(static function () {
        $logger = new \Monolog\Logger('audit');
        $handler = new \Monolog\Handler\StreamHandler('C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../logs/audit_trail.log', \Monolog\Logger::INFO);
        $handler->setFormatter(new \Monolog\Formatter\JsonFormatter());

        $logger->pushProcessor(function ($record) {
            $maskSensitive = function ($data) use (&$maskSensitive) {
                if (\is_array($data)) {
                    foreach ($data as $k => $v) {
                        $data[$k] = $maskSensitive($v);
                    }
                } elseif (\is_string($data)) {
                    if (\preg_match('/^[A-Z0-9]{16}$/i', $data)) {
                        return \substr($data, 0, 4) . '********' . \substr($data, -4);
                    }
                    if (\str_contains($data, '@')) {
                        $parts = \explode('@', $data);
                        return \substr($parts[0], 0, 1) . '***@' . $parts[1];
                    }
                }
                return $data;
            };
            $record->extra['context_masked'] = $maskSensitive($record->context);
            return $record;
        });

        $logger->pushHandler($handler);
        return $logger;
    }, 'audit_logger');
    }

    protected function get48()
    {
        return $this->resolveFactory(static function () {
        // Configurabile via ENV se necessario
        $params = [
            'scheme' => 'tcp',
            'host' => $_ENV['REDIS_HOST'] ?? '127.0.0.1',
            'port' => $_ENV['REDIS_PORT'] ?? 6379,
        ];

        try {
            return new \Predis\Client($params);
        } catch (\Exception $e) {
            // Se Redis fallisce, potremmo ritornare null o gestire l'errore
            // Per ora ritorniamo null per permettere il fallback gracefully nel codice
            return null;
        }
    }, 'Predis\\Client');
    }

    protected function get49()
    {
        return $this->resolveFactory(static function () {
        return \FratellanzaMilitare\InfrastrutturaIT\Persistence\DatabaseConnection::getConnection();
    }, 'PDO');
    }

    protected function get50()
    {
        return $this->resolveFactory(static function (\PDO $pdo) {
        return new \FratellanzaMilitare\InfrastrutturaIT\Persistence\PDOSocioRepository($pdo);
    }, 'FratellanzaMilitare\\InfrastrutturaIT\\Persistence\\PDOSocioRepository');
    }

    protected function get51()
    {
        return $this->delegateContainer->get('FratellanzaMilitare\\InfrastrutturaIT\\Persistence\\PDOSocioRepository');
    }

    protected function get52()
    {
        return $this->resolveFactory(static function () {
        $templatePaths = [
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/auth',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/soci',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/admin',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/layout',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/partials',
            'C:\\Program Files\\Ampps\\www\\fratellanza-militare-archivio\\config\\definitions' . '/../../templates/errors',
        ];

        return new \Mustache_Engine([
            'loader' => new \FratellanzaMilitare\View\CascadingLoader($templatePaths),
            'partials_loader' => new \FratellanzaMilitare\View\CascadingLoader($templatePaths),
            'escape' => function ($value) {
                return \htmlspecialchars($value ?? '', ENT_QUOTES, 'UTF-8');
            },
        ]);
    }, 'Mustache_Engine');
    }

    protected function get53()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
        $instance = \FratellanzaMilitare\SecurityLayer\AuditTrail::getInstance();
        $instance->setLogger($c->get('audit_logger'));
        $instance->setPdo($c->get(\PDO::class));
        return $instance;
    }, 'FratellanzaMilitare\\SecurityLayer\\AuditTrail');
    }

    protected function get54()
    {
        return $this->resolveFactory(static function () {
        $config = \HTMLPurifier_Config::createDefault();
        $config->set('Cache.SerializerPath', \sys_get_temp_dir());
        $config->set('HTML.Doctype', 'HTML 4.01 Transitional');
        $config->set('Core.Encoding', 'UTF-8');
        return new \HTMLPurifier($config);
    }, 'HTMLPurifier');
    }

}
