<?php

namespace FratellanzaMilitare\SecurityLayer;

class Operatore extends UtenteSistema
{
    /**
     * Carica una pratica/documento nel sistema
     * @param string $codiceFiscale Codice fiscale del socio
     * @param string $tipoPratica Tipo di pratica
     * @param array $dati Dati della pratica
     * @return bool Successo dell'operazione
     */
    public function caricaPratica(string $codiceFiscale, string $tipoPratica, array $dati): bool
    {
        // Verifica permessi
        if (!$this->hasPermission('documenti.create')) {
            throw new \RuntimeException('Permesso negato');
        }

        // Valida dati
        if (empty($codiceFiscale) || empty($tipoPratica)) {
            throw new \InvalidArgumentException('Codice fiscale e tipo pratica sono obbligatori');
        }

        // Log dell'operazione
        AuditTrail::getInstance()->logEvento(
            $this,
            'UPLOAD_DOCUMENT',
            "socio_{$codiceFiscale}_type_{$tipoPratica}"
        );

        // In produzione: salvare nel DocumentoRepository
        return true;
    }

    /**
     * Ricerca un socio nel sistema
     * @param string $criterio Criterio di ricerca ('cf', 'nome', 'matricola')
     * @param string $valore Valore da cercare
     * @return array Risultati della ricerca
     */
    public function ricercaSocio(string $criterio, string $valore): array
    {
        // Verifica permessi
        if (!$this->hasPermission('soci.read')) {
            throw new \RuntimeException('Permesso negato');
        }

        // Log della ricerca
        AuditTrail::getInstance()->logEvento(
            $this,
            'SEARCH_SOCIO',
            "criteria_{$criterio}_value_{$valore}"
        );

        // In produzione: query al SocioRepository
        // Per ora ritorna array vuoto
        return [];
    }

    /**
     * Stampa/genera un report
     * @param string $tipoReport Tipo di report da generare
     * @param array $parametri Parametri del report
     * @return string Percorso del file generato o contenuto
     */
    public function stampaReport(string $tipoReport, array $parametri = []): string
    {
        // Verifica permessi
        if (!$this->hasPermission('report.generate')) {
            throw new \RuntimeException('Permesso negato');
        }

        // Log dell'operazione
        AuditTrail::getInstance()->logEvento(
            $this,
            'GENERATE_REPORT',
            "type_{$tipoReport}"
        );

        // Genera report base in formato CSV
        $report = "Report Type: {$tipoReport}\n";
        $report .= "Generated: " . date('Y-m-d H:i:s') . "\n";
        $report .= "Generated by: {$this->Username}\n";
        $report .= "---\n";

        // In produzione: generare report reale basato sul tipo
        return $report;
    }
}
