name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      
      - uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1 # v2
        with:
          php-version: '8.2'
          coverage: none
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Run Tests (Pest)
        run: vendor/bin/pest
        
      - name: Static Analysis (PHPStan)
        run: vendor/bin/phpstan analyse src/ --memory-limit=1G
